name: Build and push to ACR
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build and push to ACR 
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2

      - name: Azure Docker login
        uses: azure/docker-login@v1
        with:
          login-server: test
          username: test
          password: test
      
      - name: Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.IMAGE_TAG }}
          file: Dockerfile